server:
    server_name: WebServer
    host: localhost
    # listen:
    #     - 80
    #     - 50
    listen: [80, 50]

    error_page:
        - "404": ./public/html/404.html
        - "405": ./public/html/405.html

    location:
        path: /login
        root: ./public/html
        allow_methods: [GET, POST, DELETE]
        autoindex: on
        body_size: 15000
        redirection: "google.com"
