server:
    - server_name: WebServer
      root: /public
      listen: [8080]
      max_body_size: 15000
      error_pages:

      locations:
          - name: login
            path: /login
            root: ./resources/html
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            redirection: google.com
            destination: 
            cgi_destinaation: 

          - name: Images
            path: /imgs
            root: ./resources/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi

          - name: Images
            path: /
            root: ./resources
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi
