server:
    - server_name: WebServer
      root: /public
      listen: [80, 50]
      error_pages:

      locations:
          - name: login
            path: /login
            root: ./public/html
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 15000
            redirection: google.com
            destination: 
            cgi_destinaation: 

          - name: Images
            path: /imgs
            root: ./public/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi


    - server_name: WebServer
      root: /public
      listen: [80, 50, 69, 42]
      error_pages:
          - 404: ./public/html/404.html
          - 405: ./public/html/405.html
          - 406: ./public/html/foca.html

      locations:
          - name: login
            path: /login
            root: ./public/html
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 15000
            redirection: google.com
            destination: 
            cgi_destinaation: 

          - name: Images
            path: /prdrtdrt
            root: ./public/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi

          - name: Images
            path: /focas
            root: ./public/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi
