server:
    - server_name: WebServer
      root: /public
      listen: [8080]
      error_pages:

      locations:
          - name: login
            path: /login
            root: ./public/html
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 15000
            redirection: google.com
            destination: 
            cgi_destinaation: 

          - name: Images
            path: /imgs
            root: ./public/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi


    - server_name: AJO 
      root: /public
      listen: [9090]
      error_pages:

      locations:
          - name: login
            path: /login
            root: ./public/html
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 15000
            redirection: google.com
            destination: 
            cgi_destinaation: 

          - name: Images
            path: /imgs
            root: ./public/html
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            max_body_size: 
            redirection: "google.com"
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi
