server:
    - server_name: WebServer
      root: /resources
      listen: [8080]
      max_body_size: 15000
      error_pages:
          - 404: ./resources/html/404.html
          - 405: ./resources/html/405.html
          - 406: ./resources/html/foca.html

      locations:
          - name: Post
            path: /post
            root: ./resources
            index: post.html
            allowed_methods: [GET, DELETE]
            autoindex: off
            redirection: 
            destination: 
            cgi_destinaation: 

          - name: Gallery
            path: /images
            root: ./resources
            index: gallery.php
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi

          - name: default
            path: /
            root: ./resources
            index: index.html
            allowed_methods: [POST, DELETE]
            autoindex: off
            redirection: 
            destination: ./images #direccion donde se guarda el POST
            cgi_destinaation: ./cgi-bin #direccion del cgi