server:
    - server_name: WebServer
      root: 
      listen: [8080]
      max_body_size: 
      error_pages:
          - 404: ./resources/html/404.html
          - 406: ./resources/html/foca.html
          - 500: ./resources/html/500.html

      locations:
          - name: Post
            path: /post
            root: ./resources
            index: post.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: bin
            cgi_destinaation: 

          - name: Gallery
            path: /images
            root: ./resources
            index: gallery.php
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: images
            cgi_destinaation: ./cgi-bin

          - name: default
            path: /
            root: ./resources
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: images
            cgi_destinaation: ./cgi-bin

          - name: a
            path: /a
            root: ./resources
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: images
            cgi_destinaation: ./cgi-bin
