server:
    - server_name: pallete
      listen: [8080]
      max_body_size: 1
      error_pages:
          - 404: ./resources/html/404.html
          - 406: ./resources/html/foca.html
          - 500: ./resources/html/500.html

      locations:
          - name: Test
            path: /cosas
            root: ./resources
            index: 
            allowed_methods: [GET, POST, DELETE]
            autoindex: on
            redirection: 
            destination: images

          - name: Post
            path: /post
            root: ./resources
            index: post.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: bin

          - name: Gallery
            path: /images
            root: ./resources
            index: gallery.php
            allowed_methods: [GET, POST]
            autoindex: off
            redirection: 
            destination: images

          - name: default
            path: /
            root: ./resources
            index: index.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: images

          - name: a
            path: /a
            root: ./resources/siege
            index: siegetest.html
            allowed_methods: [GET, POST, DELETE]
            autoindex: off
            redirection: 
            destination: images
